### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by huolingfeng210** [ederwander/Beat-Track#1]
Hi,  Thank you for your  shared code, but I find some trouble.
1.   frequency bands "Scheirer"    200, 400, 800, 1600, 3200, 6400, but  the pulled code is as follow:
      [SubBand1, numerator1, denominator1]=SubBandDWT(Signal,Fs,1,2000);
      [SubBand2, numerator2, denominator2]=SubBandDWT(Signal,Fs,2000,4000);
2.   SubBandDWT is completed by butter bandpass filter, firstly high pass and then low pass, rathe than     discrete wavelet transform method.
3.     low pass filter processing in Envelope function   is the same  as low pass filter processing in SubBandDWT function.  why twice?

**Comment by ederwander** [comment]
Hi thanks to point me.

I wrote this code in a few hours Its will not work 100% this was a quick conceptual test,  so i skipped the DWT and just bandpass the signal, the frequency bands are wrong in the code (i'm fixing), the last low pass flter can be skipped its uses Convolution to get envelope. You maybe will test different decimation to try more accurate results.

**Comment by huolingfeng210** [comment]
Thank you for your advice, actually I just want to obtain beat map histogram,not detect BPM. 
In addition, I ask a signal processing question.
As known, range of BPM is about from  60~250, which means that we just need partials below 250Hz.
but in many paper,  audio  is processed in many subbands,which are above 250Hz and useless  theoretically. 
on the other hand,  I check the figure of SubBand1  SubBand2 ... SubBand6 data, and find the exsiting periodicity in all of subbands. can you explain it to me?

**Comment by ederwander** [comment]
For Beat Histogram its will works nice...

Is true if you look just for strong rhythmic songs where the beats are in essence in the low frequencies, so for this kind of songs you need just bandpass 1-200Hz, But and the other kinds of songs? where the beat of the song is around all the other frequencies ? so the sum of all this envelope frequencies give to you one better shot, try plot the envelopes and than take a look in the sum from all envelope, you can see how the summ give a better preception from the beats in all frequencie range (200-6400).

You can imagine that as well as take autocorrelation from each envelope position between 75 and 375.

Max BPM 200 in decimed envelope
ceil((60 \* 250) / (200))

ans =

```
75
```

Min BPM 40 in decimed envelope
ceil((60 \* 250) / (40))

ans =

   375

**Comment by huolingfeng210** [comment]
yes, I know detecting period just like detecting pitch in speech by autocorrelation.
I think reasons may be  as follow:
In fact, waveform peaks occurs in  similarlly fixed time interval, so it is the same that  peaks occurs periodically in frequency domain, which means  frequency above 250Hz is  useful   because  interval between peaks(harmonics) is periodicity. so adding  all of   subands  can enhance periodicity.
do you agree with me?
